name = "Humpty"
uuid = "f0ed2d8d-fccb-4d7b-87b7-3b5a26c7bcd5"
authors = ["Frames White <frames.white@invenialabs.co.uk> and contributors"]
version = "1.0.0"

[deps]
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[compat]
julia = "1"
ChainRules = "1.47"
ChainRulesCore = "1.15.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
